export const GET_COUNTRY_LIST_REQUEST = 'GET_COUNTRY_LIST_REQUEST';
export const GET_COUNTRY_LIST_SUCCESS = 'GET_COUNTRY_LIST_SUCCESS';
export const GET_COUNTRY_LIST_FAIL = 'GET_COUNTRY_LIST_FAIL';

export const GET_CITY_LIST_REQUEST = 'GET_CITY_LIST_REQUEST';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_LIST_FAIL = 'GET_CITY_LIST_FAIL';

export const GET_STATE_LIST_REQUEST = 'GET_STATE_LIST_REQUEST';
export const GET_STATE_LIST_SUCCESS = 'GET_STATE_LIST_SUCCESS';
export const GET_STATE_LIST_FAIL = 'GET_STATE_LIST_FAIL';

export const GET_INDUSTRY_LIST_REQUEST = 'GET_INDUSTRY_LIST_REQUEST';
export const GET_INDUSTRY_LIST_SUCCESS = 'GET_INDUSTRY_LIST_SUCCESS';
export const GET_INDUSTRY_LIST_FAIL = 'GET_INDUSTRY_LIST_FAIL';

export const GET_ALL_LISTS_REQUEST = 'GET_ALL_LISTS_REQUEST';
export const GET_ALL_LISTS_SUCCESS = 'GET_ALL_LISTS_SUCCESS';

export const GET_STORE_INFO_REQUEST = 'GET_STORE_INFO_REQUEST';
export const GET_STORE_INFO_SUCCESS = 'GET_STORE_INFO_SUCCESS';
export const GET_STORE_INFO_FAIL = 'GET_STORE_INFO_FAIL';
